version: "3"

services:
  nextjs-app:
    container_name: next-app
    build:
      context: .
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
